Optimise image upload s #168
content-is-queen/creator-platform-be pull request #173
Opened 2024-06-05 11:13 UTC by Mundurujoana

## Describe your changes

e.g Introduces a new function to manage user profiles

## Issue ticket number and link

e.g Closes #123 & #234

Reminder: please remember to run `npm run format` before opening PR

2024-06-26 10:02 UTC, Kaleshe requested changes

2024-06-26 12:37 UTC, Mundurujoana commented
Okay 👍

On Wed, 26 Jun 2024, 12:02 Kaleshe, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/restful/controllers/authController.js
> <https://github.com/content-is-queen/creator-platform-be/pull/173#discussion_r1652869073>
> :
>
> > +        console.log(`Processed file size: ${processedFileSize} bytes`);
> +
> +        // Check the dimensions of the processed image
> +        const metadata = await sharp(outputFilePath).metadata();
> +        console.log(
> +          `Processed image dimensions: ${metadata.width}x${metadata.height}`,
> +        );
> +
> +        // Ensure the dimensions are within the limits
> +        if (metadata.width > 200 || metadata.height > 200) {
> +          throw new Error("Processed image dimensions exceed 200x200 pixels");
> +        }
> +
> +        const storageRef = admin
> +          .storage()
> +          .bucket(`gs://contentisqueen-97ae5.appspot.com`);
>
> We shouldn't be hardcoding the bucket location
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/content-is-queen/creator-platform-be/pull/173#pullrequestreview-2138753541>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXWIZOD4RXS6JIP252ZRAGDZJKGTBAVCNFSM6AAAAABI2PSWDKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMZYG42TGNJUGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-06-28 13:20 UTC, closed without merging

2024-06-28 16:05 UTC, Kaleshe commented
We're now uploading directly to bitbucket so no need to optimise in our backend

2024-06-28 16:36 UTC, Mundurujoana commented
Okay!